[package]
name = "antelope-firewall"
version = "0.1.0"
edition = "2021"

[dependencies]
hyper = { version = "1.0.0-rc.3", features = ["full"] }
tokio = { version = "1", features = ["full"] }
http-body-util = "0.1.0-rc.2" 
reqwest = { version = "0.11.18", features = ["json"] }

