[package]
name = "antelope-firewall"
version = "0.1.0"
edition = "2021"

[dependencies]
antelope-firewall-lib = { path = "../antelope-firewall-lib/" }
clap = { version = "4.3.11", features = ["derive"] }
tokio = { version = "1.28.2", features = ["full"] }
toml = "0.7.6"
